### PR TITLE
Add nextest compatibility

### PR DESCRIPTION
**Pull request by sunshowers**
This commit stack makes criterion compatible with nextest using the rules [listed here](https://nexte.st/book/custom-test-harnesses.html). Each commit is independently reviewable.

Note that none of these changes do anything special for nextest -- they just make criterion implement more of the libtest command-line interface, just enough to make nextest happy.

Addresses #562 -- once this commit stack lands and a new version of criterion goes out, I'd be happy to advertise compatibility on the nextest site.

### CODE REVIEW

**Comment by sunshowers** [comment]
(Let me know if I should target 0.4 or master for this)

**Comment by aldanor** [comment]
This is awesome, would be great to have this reviewed and land. Wonder if there is anything blocking?

**Comment by bheisler** [comment]
No, the only blocker is that I have limited time and energy to spend on open-source work lately. My apologies for the delay, I'll try to get to it at some point.

**Comment by sunshowers** [comment]
@lemmih do you think you'd be able to get a version out with this soon? Had another request come in today.

**Comment by lemmih** [comment]
Releases are managed by @bheisler.

**Comment by sunshowers** [comment]
Hi @bheisler, do you think you'd be able to make a release soon? Thank you so much for maintaining criterion!

**Comment by lemmih** [comment]
> Hi @bheisler, do you think you'd be able to make a release soon? Thank you so much for maintaining criterion!

Brook gave me permission to release a new version. Think you could help me update the `CHANGELOG.md`? We probably also want to review https://github.com/bheisler/criterion.rs/pull/679 before cutting a release.

**Comment by sunshowers** [comment]
Thanks @lemmih. Happy to spend some time on this tomorrow. What would be a good way to coordinate our efforts?

**Comment by lemmih** [comment]
> Thanks @lemmih. Happy to spend some time on this tomorrow. What would be a good way to coordinate our efforts?

If you begin updating the changelog, put the changes in a draft PR.

**Comment by nbarrios1337** [comment]
work-in-progress updates for the changelog -> #680

**Pull request merged**
