### PR TITLE
Bump MSRV to 1.60 for csv dependency

### PR DESCRIPTION
**Pull request by nbarrios1337**

### CODE REVIEW

**Comment by lemmih** [comment]
Hmm, I don't know why the CI fails.

**Comment by nbarrios1337** [comment]
I've found recent criterion.rs PRs merge through regardless of the failing appveyor CI. However, the "unknown" error from the GHA run is unclear to me as well.

Edit: doing some WIP ci debugging at nbarrios1337/criterion.rs#2

**Comment by nbarrios1337** [comment]
The CI here and over on nbarrios1337/criterion.rs#2 successfully builds and tests (until canceled at least) across all tested toolchains, but fails on clippy lints on the stable toolchain run.

I can go ahead and fix those lints; Are there some nuances for the criterion.rs source code where I should place an `#[allow(...)]` for lints that can be specifically ignored?

**Comment by lemmih** [comment]
> I can go ahead and fix those lints; Are there some nuances for the criterion.rs source code where I should place an `#[allow(...)]` for lints that can be specifically ignored?

Everything can probably be fixed.

**Review by lemmih — APPROVED** [review]

**Pull request merged**
