### PR TITLE
replace `serde_cbor` with `ciborium`

### LINKED ISSUE #534: `serde_cbor` is unmaintained (RUSTSEC-2021-0127)
As per [RUSTSEC-2021-0127](https://rustsec.org/advisories/RUSTSEC-2021-0127) `serde_cbor` is unmaintained. Would be nice if it could be replaced by [`ciborium`](https://crates.io/crates/ciborium) or [`minicbor`](https://crates.io/crates/minicbor).

I can take care of that, but I've seen #496 is currently in progress so I'm wondering if this should target `master` or `version-0.4`?

### PR DESCRIPTION
**Pull request by crepererum**
Fixes #534.

### CODE REVIEW

**Comment by lemmih** [comment]
Looks good. Could you change the target from `master` to `version-0.4`?

**Comment by crepererum** [comment]
> Looks good. Could you change the target from `master` to `version-0.4`?

done

**Comment by crepererum** [comment]
Mmh, `ciborium` 0.2 uses Rust edition 2021, which is available as of Rust 1.56. I could try to downgrade to `ciborium` 0.1 (which uses Rust edition 2018) or we could bump the MSRV for the upcoming 0.4 criterion release. What do you think?

**Comment by lemmih** [comment]
Let's bump the MSRV to 1.56.

**Comment by crepererum** [comment]
@lemmih I've bumped the MSRV, but since this touches the GitHub workflow this change needs your approval to run on CI.

**Comment by jhpratt** [comment]
Any chance this can be merged & released? The diff LGTM and the dependency is causing security advisories due to it being unmaintained.

**Comment by vorot93** [comment]
@bheisler @lemmih could this be merged to address downstream security advisories?

**Comment by lemmih** [comment]
Merging. Will work on releasing 0.4

**Pull request merged**
