### PR TITLE
Update to async-std v1.13

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Review by waywardmonkeys — COMMENTED** [review]
Is there a security reason or otherwise to *require* the newer version rather than allow this to work for people who are (for whatever reason) on an older version?

**Comment by jayvdb** [comment]
There are no relevant CVEs.

However, is there a security problem somewhere in async-std [v1.9](https://github.com/async-rs/async-std/releases/tag/v1.9.0), 3.5 years ago, and its deps? 

I'd put good money on it.

There are 133 commits in https://github.com/async-rs/async-std/compare/v1.9.0...main

Anyway, feel free to close if you feel this PR doesnt improve criterion.

**Comment by jayvdb** [comment]
fwiw, criterion has a MSRV of 1.70 https://github.com/bheisler/criterion.rs/pull/813 , while async-std is 1.63 https://github.com/async-rs/async-std/pull/1087

**Comment by waywardmonkeys** [comment]
Seems fine to merge to me. Up to @bheisler though.

**Comment by waywardmonkeys** [comment]
I meant to tag @lemmih here...

**Review by waywardmonkeys — APPROVED** [review]
LGTM

**Pull request merged**
