### PR TITLE
fix: missing closing parenthesis in examples

### PR DESCRIPTION
**Pull request by erwanvivien**
user_guide/advanced_configuration was missing closing parenthesis when calling bench_function

### CODE REVIEW

**Review by lemmih — APPROVED** [review]

**Comment by erwanvivien** [comment]
Thanks lemmih for approving this pull request.
Should I do anything now ?

**Comment by lemmih** [comment]
> Thanks lemmih for approving this pull request.
> Should I do anything now ?

Nope, everything checked out just fine.

**Comment by wathiede** [comment]
I just noticed the same error on https://bheisler.github.io/criterion.rs/book/index.html and was about to make this same pull request. 

Is there some automation that is broken that has prevented this from going live over the last half year?  Even if it's tied to releases, it looks like 0.4.0 happened after this change was merged.

**Comment by erwanvivien** [comment]
I was wondering the same, do you have an insight @lemmih ?

**Comment by lemmih** [comment]
Not sure. Maybe the book has to be manually pushed.

**Pull request merged**
