### PR TITLE
Depend on itertools >=0.10, <0.12

### PR DESCRIPTION
**Pull request by sjackman**
Depend on itertools >=0.10, <0.12

### CODE REVIEW

**Comment by sjackman** [comment]
`error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256' to 'C:\Users\appveyor\.rustup\tmp\81ucn_6cqhsxtqhp_file': failed to make network request: error sending request for url (https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256): error trying to connect: The message received was unexpected or badly formatted. (os error -2146893018): error trying to connect: The message received was unexpected or badly formatted. (os error -2146893018): The message received was unexpected or badly formatted. (os error -2146893018)
Command exited with code 1`
https://ci.appveyor.com/project/bheisler/criterion-rs/builds/47373637/job/agikfswe8n4heksh#L16

**Comment by sjackman** [comment]
In the previous build https://ci.appveyor.com/project/bheisler/criterion-rs/builds/47373637
✅ Environment: TARGET=x86_64-pc-windows-msvc, GNUPLOT=yes
❌ Environment: TARGET=x86_64-pc-windows-msvc, GNUPLOT=no

In the current build (with no change to code) https://ci.appveyor.com/project/bheisler/criterion-rs/builds/47373729
❌ Environment: TARGET=x86_64-pc-windows-msvc, GNUPLOT=yes
❌ Environment: TARGET=x86_64-pc-windows-msvc, GNUPLOT=no

**Comment by sjackman** [comment]
@lemmih Is there anything I need to change in this PR to get the AppVeyor CI check passing?

**Comment by lemmih** [comment]
> @lemmih Is there anything I need to change in this PR to get the AppVeyor CI check passing?

You could make a separate PR that gets rid of AppVeyor.

**Comment by sjackman** [comment]
> You could make a separate PR that gets rid of AppVeyor.

Done!

- https://github.com/bheisler/criterion.rs/pull/699

**Comment by sjackman** [comment]
@lemmih Thank you for merging my PR #699 to remove AppVeyor! Looks like this PR is now passing CI and good to go.

**Comment by sjackman** [comment]
@lemmih Thank you for merging this PR, David. Could you please push a new stable release to crates.io including this change when you have time?

**Pull request merged**
