### PR TITLE
ci: Fix MSRV build by precisely specifying some deps.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This also stops the build from cancelling all jobs once one fails, so that we can see the results for each version of Rust tested. Otherwise, the `stable` job fails (due to clippy) and we don't get results for the MSRV build.

**Comment by waywardmonkeys** [comment]
#729 fixes the `stable` build and can be rebased forward and land once this one does.

**Comment by lemmih** [comment]
How about joining the two PRs? I'd feel much better about merging a PR that passes all the checks.

**Comment by waywardmonkeys** [comment]
@lemmih Okay, I've added the single commit here that should fix the current clippy build. The other PR contains further changes that go beyond just fixing the build.

**Pull request merged**
