### PR TITLE
Provide iter_custom

### PR DESCRIPTION
**Pull request by gz**
Took a stab at handling the issue https://github.com/bheisler/criterion.rs/issues/265.
Provides a vary basic implementation of iter_custom, let me know if this is what you had in mind as an  interface.

### CODE REVIEW

**Comment by bheisler** [comment]
Hey, thanks for the pull request. This looks good so far (although I spotted a typo - "scnearios").

I'd like to discuss the design a bit, though. What you have here is good, but this will interact with the new custom measurements feature in 0.3.0 which allows for custom implementations of a `Measurement` trait to measure different things than just wall-clock time and to return different types than just Duration. However, we still need to have a Duration to allow Criterion.rs to perform its warmup phase for the right length of time. This leaves a few options:

- We could set up the impl's so that the lambda passed to `iter_custom` returns just a Duration, and then set up the impls so that it can only be used with measurements that also return Duration. This is obviously restrictive, but it also means that we can't really extend it to work with custom measurements without a breaking change later.
- The lambda could instead return a tuple of Duration and Measurement::Value, to allow it to work with custom measurements, but this would impose more work on people using iter_custom. It also means that measurements that do naturally return a Duration have to return the argument twice, which is kind of awkward.
- We could have the lambda just return Measurement::Value and infer the duration based on how long it takes to execute the lambda. This is how the other measurements work, and it's how I'd prefer to implement this, but there may be some use cases where the time to execute the lambda doesn't accurately represent how long it takes to call the function (eg. if you have to spin up an external process).

I'm not sure what makes sense here. What do you think?

**Comment by gz** [comment]
> We could have the lambda just return Measurement::Value and infer the duration based on how long it takes to execute the lambda. This is how the other measurements work, and it's how I'd prefer to implement this, but there may be some use cases where the time to execute the lambda doesn't accurately represent how long it takes to call the function (eg. if you have to spin up an external process).

That case wouldn't fit with our use-case, I think (and the one discussed in #265). We are benchmarking a set-up which spawns multiple threads and synchronizes the timing measurement using a barrier. Which is difficult to do precisely if we just measure the lambda (set-up overhead is large). 

> The lambda could instead return a tuple of Duration and Measurement::Value, to allow it to work with custom measurements, but this would impose more work on people using iter_custom. It also means that measurements that do naturally return a Duration have to return the argument twice, which is kind of awkward.

I see, I'm not familiar with the Measurement type and how it works in 0.3 (aside: could the Duration just be embedded to be always included in the Measurement::Value and (be overridden by the lambda in iter_custom)). Other than that, this seems like an acceptable trade-off, given that the only time a user does iter_custom is when he has a pretty special use-case anyways.

**Comment by bheisler** [comment]
That's fair. You're right that `iter_custom` is only needed for unusual cases, so it's not unreasonable to expect callers to do a bit more work.

Would you mind rebasing this onto the `v0.3.0-dev` branch?

**Comment by bheisler** [comment]
I've merged this into v0.3.0-dev manually. Thanks for the pull request!

**Comment by gz** [comment]
Thanks, sorry I was unable to respond to this due to an accident.

**Pull request closed without merging**
